# Generated by Django 5.0.6 on 2024-05-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0004_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='itens',
            field=models.ManyToManyField(related_name='orders', to='order_manager.item'),
        ),
    ]
